[phases.setup]
pkgs = [
    # Debian package names (not Alpine):
    "zlib1g-dev",
    "libjpeg-dev",
    "libwebp-dev",
    "libopenjp2-7-dev",
    "libtiff5-dev",
    "libfreetype6-dev",
    "python3-dev"  # Required for Python headers
]

[phases.build]
commands = [
    "python manage.py collectstatic --noinput"

[phases.start]
cmd = "gunicorn djangoProject.wsgi --bind 0.0.0.0:$PORT"
